# Generated by Django 5.0.6 on 2024-05-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
