# Generated by Django 5.0.6 on 2024-05-24 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_goals_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance', models.IntegerField(choices=[(1, 'unacceptable'), (2, 'poor'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, max_length=200)),
                ('improvements', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goals',
            name='pirority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Midium'), (3, 'Low')], default=3),
        ),
        migrations.AddField(
            model_name='tasks',
            name='pirority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Midium'), (3, 'Low')], default=3),
        ),
        migrations.AlterField(
            model_name='categories',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskPerformace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance', models.IntegerField(choices=[(1, 'unacceptable'), (2, 'poor'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=1)),
                ('reasons', models.TextField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True, max_length=100)),
                ('tomorrows_plan', models.TextField(blank=True, max_length=100)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taks_review', to='API.journal')),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfromance', to='API.tasks')),
            ],
        ),
    ]
