# Generated by Django 5.0.6 on 2024-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_categories_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='did_start_on_time',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'onetime'), (2, 'regular')], default=2),
        ),
    ]
