# Generated by Django 5.0.6 on 2024-05-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_journal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='pirority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='pirority',
            new_name='priority',
        ),
    ]
