# Generated by Django 5.0.6 on 2024-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_tasks_completion_alter_tasks_did_start_on_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='actual_start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
