# Generated by Django 5.0.6 on 2024-05-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_tasks_actual_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='API.goals'),
        ),
    ]
