# Generated by Django 5.0.6 on 2024-05-30 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_tasks_related_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
