# Generated by Django 5.0.6 on 2024-05-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_tasks_actual_start_time_alter_tasks_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='API.tasks'),
        ),
    ]
