# Generated by Django 5.0.6 on 2024-05-30 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_tasks_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='worked_for',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
