# Generated by Django 5.0.6 on 2024-05-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_goals_worked_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='completion',
            field=models.FloatField(default=0),
        ),
    ]
